export const US_UNIVERSITIES = [
  "Alabama State University",
  "Arizona State University",
  "Boston College",
  "Boston University",
  "Brandeis University",
  "Brown University",
  "California Institute of Technology (Caltech)",
  "Carnegie Mellon University",
  "Case Western Reserve University",
  "Clemson University",
  "Colgate University",
  "Colorado School of Mines",
  "Columbia University",
  "Cornell University",
  "Dartmouth College",
  "Duke University",
  "Emory University",
  "Florida State University",
  "Florida Polytechnic University",
  "George Mason University",
  "George Washington University",
  "Georgetown University",
  "Georgia Institute of Technology",
  "Harvard University",
  "Harvey Mudd College",
  "Indiana University",
  "Iowa State University",
  "Johns Hopkins University",
  "Lehigh University",
  "Massachusetts Institute of Technology (MIT)",
  "Miami University",
  "Michigan State University",
  "Michigan Technological University",
  "New York University (NYU)",
  "Northwestern University",
  "Ohio State University",
  "Oregon State University",
  "Penn State University",
  "Princeton University",
  "Purdue University",
  "Rensselaer Polytechnic Institute",
  "Rice University",
  "Rutgers University",
  "Southern Methodist University",
  "Stanford University",
  "Stevens Institute of Technology",
  "Syracuse University",
  "Texas A&M University",
  "Texas Tech University",
  "University of Alabama",
  "University of Arizona",
  "University of California, Berkeley",
  "University of California, Davis",
  "University of California, Irvine",
  "University of California, Los Angeles (UCLA)",
  "University of California, San Diego",
  "University of California, Santa Barbara",
  "University of Chicago",
  "University of Colorado Boulder",
  "University of Connecticut",
  "University of Delaware",
  "University of Florida",
  "University of Georgia",
  "University of Illinois Urbana-Champaign",
  "University of Iowa",
  "University of Kansas",
  "University of Kentucky",
  "University of Maryland",
  "University of Massachusetts Amherst",
  "University of Miami",
  "University of Michigan",
  "University of Minnesota",
  "University of Mississippi",
  "University of Missouri",
  "University of Nebraska",
  "University of Nevada, Las Vegas",
  "University of New Hampshire",
  "University of North Carolina at Chapel Hill",
  "University of North Dakota",
  "University of Notre Dame",
  "University of Oklahoma",
  "University of Pennsylvania",
  "University of Pittsburgh",
  "University of Rochester",
  "University of South Carolina",
  "University of South Dakota",
  "University of Southern California (USC)",
  "University of Texas at Austin",
  "University of Texas at Dallas",
  "University of Utah",
  "University of Virginia",
  "University of Washington",
  "University of Wisconsin-Madison",
  "University of Wyoming",
  "Vanderbilt University",
  "Virginia Polytechnic Institute",
  "Wake Forest University",
  "Washington University in St. Louis",
  "Wellesley College",
  "Wesleyan University",
  "West Virginia University",
  "Yale University",
];
